### PR TITLE
Adding tabindex support

### LINKED ISSUE #9: Can't set tabindex
I'll open a pull request with a fix.

### PR DESCRIPTION
**Pull request by nadavshatz**
Closes #9

### CODE REVIEW

**Comment by begedin** [comment]
Good job.

**Comment by nadavshatz** [comment]
Can you please release a new version to NPM? or did you do already?

**Comment by begedin** [comment]
@nadavshatz I just did. Sorry, didn't get a chance to earlier.

**Comment by nadavshatz** [comment]
@begedin no problem. Thanks!

**Pull request merged**
